### ISSUE TITLE
Remote Kable tables are returned as text

### ISSUE THREAD

**Issue by margaret-colville** [databrickslabs/brickster#57]
When I run a table through `kable()` on a `databricks_r` block, it is rendered as the "Send it to the console" version, not the "Styled for production" version.  `kableExtra` tables are even worse, printing out every HTML tag (even when rendering to LaTeX).

[kable-tables.zip](https://github.com/user-attachments/files/16326889/kable-tables.zip)

**Comment by zacdav-db** [comment]
Removing `knitr` engine from package in next version.
