### ISSUE TITLE
Inline code does not render as the result, for remote blocks

### ISSUE THREAD

**Issue by margaret-colville** [databrickslabs/brickster#59]
If I try to include a line of inline code for a remote block in my RMarkdown prose, it instead displays the command text in code styling.
[inline-text.zip](https://github.com/user-attachments/files/16326923/inline-text.zip)

**Comment by zacdav-db** [comment]
Unfortunately this isn't something brickster can overcome. It's a limitation of knitr.

e.g. You cannot run this either:
````
`python 1+1`
````


Quarto only now can do this but it requires specific engine settings and still won't work for the brickster knitr engines.

e.g. This works for Quarto but not for RMarkdown
````
```{r}
radius <- 5
```

The radius of the circle is `{r} radius`
````

More on quarto inline **[here](https://quarto.org/docs/computations/inline-code.html)**
