### ISSUE TITLE
fig.cap cannot be set dynamically for remote blocks

### ISSUE THREAD

**Issue by margaret-colville** [databrickslabs/brickster#61]
`fig.cap`'s handling is odd - it can work with statically assigned captions, but if I try to dynamically assign a caption to a remote block, I receive "`object of type 'symbol' is not subsettable`" and the rmd entirely refuses to render.
[fig-cap.zip](https://github.com/user-attachments/files/16326944/fig-cap.zip)

**Comment by zacdav-db** [comment]
Removing `knitr` engine from package in next version.
