### ISSUE TITLE
Databricks python doesn't include folium

### ISSUE THREAD

**Issue by margaret-colville** [databrickslabs/brickster#62]
The "How to use Brickster" RMarkdown template includes a block demonstrating the use of the `engine = "databricks_py"` parameter.  However, it is calling on a library called `folium`, which does not seem to be installed by default on Databricks' python install, so the file cannot render.  Is there a different sample block that is more likely to work for the user?
[fig-height-fig-width.zip](https://github.com/user-attachments/files/16326974/fig-height-fig-width.zip)

**Comment by zacdav-db** [comment]
Addressed in #64.
