### ISSUE TITLE
Add option to allow db_host() and db_token() to follow DATABRICKS_CONFIG_FILE

### ISSUE THREAD

**Issue by tnederlof** [databrickslabs/brickster#65]
Currently the `db_host()` and `db_token()` functions will look in `HOME` for a `.databrickscfg` file and this is [not configurable](https://github.com/databrickslabs/brickster/blob/46cd34aad31a40387d37d43621626b2096febe9d/R/package-auth.R#L163). Some environments such as Posit Workbench put the `.databrickscfg` in an alternative location which needs to be followed.

The Databricks CLI will look for `.databrickscfg` in a users home directory by default but if `DATABRICKS_CONFIG_FILE ` is set, it will look in an alternative path as outlined here: [https://docs.databricks.com/en/dev-tools/cli/profiles.html](https://docs.databricks.com/en/dev-tools/cli/profiles.html).

Adding this to brickster would make using the package in these environments much more straight forward.

**Comment by zacdav-db** [comment]
Added some comments in PR. Definitely want to make this work well in workbench!
