### ISSUE TITLE
`db_volume_delete` bad type

### ISSUE THREAD

**Issue by vladimirobucina** [databrickslabs/brickster#73]
There is an error on this line: https://github.com/databrickslabs/brickster/blob/c032a87a0d05e7b31a4f43c4312c662b2c4a1a89/R/volume-fs.R#L46

Should be changed to `files` instead of `directories`.

**Comment by zacdav-db** [comment]
Good pickup! Would you mind making a simple PR and I can merge?

**Comment by vladimirobucina** [comment]
Yes,  I'll fork the repo, and make a PR :)
